title: Ewan Burnett Development Blog
author: Ewan Burnett
email: EwanBurnett@Hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Simple blog page for my projects.

# social links
twitter_username: EwanBurnett # DO NOT include the @ character, or else the build will fail!
github_username:  EwanBurnett # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
